# Generated by Django 4.1.6 on 2023-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='like_count'),
        ),
    ]
